'use strict';
/**
 * deploy-guide.js — generates docs/tealium-deployment.md: a copy-paste runbook for
 * putting the repo's extensions, tags, and load rules into the live Tealium iQ profile
 * in the correct scope + order, then validating them with Trace. Generated from the
 * manifests so it never drifts from the code.
 */
const fs = require('fs');
const path = require('path');
const { loadMetadata, loadPolicy, ROOT } = require('./lib/load-policy');

function run() {
  const profile = loadMetadata();
  const policy = loadPolicy();
  const exts = [...profile.extensions].sort((a, b) => a.loadRank - b.loadRank);
  const REPO_BLOB = 'https://github.com/Mr-orchestrator/tealium-extensions/blob/main/';

  let md = `<!-- GENERATED by scripts/deploy-guide.js — do not edit by hand -->\n`;
  md += `# Tealium Deployment & Validation Runbook — \`cognizant-sandbox / f1racing\`\n\n`;
  md += `Deploy these ${exts.length} extensions, ${Object.keys(profile.tags).length} tags and load rules into the Tealium iQ profile, **in this order**, then validate with Trace.\n\n`;
  md += `**Recommended — keep the repo as the source of truth:** in each extension use **Add GitHub File** and paste its GitHub URL (below) instead of copy-pasting code. Tealium loads the code from GitHub, so a repo change (after CI passes) flows to Tealium on republish. The linked GitHub account must have access to this repo.\n\n`;

  md += `## 1. Load rules\n\nAll extensions/tags use load rule **All Pages** (\`all\`). Create one load rule "All Pages" with condition \`true\` (or use the built-in All Pages).\n\n`;

  md += `## 2. Extensions (create in this scope + order)\n\n`;
  md += `In Tealium iQ → **Extensions → + Add Extension → JavaScript Code**. Set the **Scope** and drag to the **Order** shown, then paste the code.\n\n`;
  exts.forEach((e, i) => {
    const code = fs.readFileSync(path.join(ROOT, e.file), 'utf8');
    md += `### ${i + 1}. ${e.name}${e.protected ? ' 🔒' : ''}\n`;
    md += `- **Scope:** ${e.scope} · **Order:** ${e.order} · **Load rule:** All Pages · **Risk:** ${e.risk}\n`;
    md += `- **Add GitHub File URL:** ${REPO_BLOB}${e.file}\n`;
    md += `- **Creates:** ${(e.creates || []).join(', ') || '—'}\n`;
    md += `- **Uses:** ${(e.uses || []).join(', ') || '—'}\n`;
    if (e.feedsTag) md += `- **Feeds tag:** ${e.feedsTag} (${e.tagCategory})\n`;
    md += `\n\`\`\`javascript\n${code.trim()}\n\`\`\`\n\n`;
  });

  md += `## 3. Tags\n\nIn Tealium iQ → **Tags → + Add Tag**. Each is fed by its mapping extension above and is gated by consent.\n\n`;
  Object.values(profile.tags).forEach(t => {
    const fed = t.fedBy.map(id => exts.find(e => e.id === id)).filter(Boolean);
    const gate = t.category === 'Marketing' ? 'consent_marketing' : 'consent_analytics';
    md += `### ${t.name} (${t.category})\n`;
    md += `- **Load rule:** All Pages — **consent-gated** by \`${gate}\` (the mapping extension returns early without consent).\n`;
    md += `- **Fed by:** ${fed.map(e => e.name).join(', ')}\n`;
    md += `- **Map these UDO variables in the tag's Data Mappings:** ${fed.flatMap(e => e.creates).join(', ')}\n\n`;
  });

  md += `## 4. Save & publish\n\n`;
  md += `Use **Save As** (never Overwrite) to preserve versions for rollback, then **Publish to qa**.\n\n`;

  md += `## 5. Validate inside Tealium (all of them)\n\n`;
  md += `1. **Trace:** Tealium iQ → **Trace** → *Start trace* → copy the trace token → open the F1 site (loader already installed) and append the trace token. The timeline shows each extension firing in **scope/order**, variables populating, and tags sending.\n`;
  md += `2. **Console (utagdb):** in the browser console run \`utag.cfg.utagdb=true\` then reload — the **Cleanup & Diagnostics** extension prints a per-event summary (\`[F1] event=… consent=… user=… ga4=… adobe=…\`).\n`;
  md += `3. **Checklist — confirm on the live site:**\n`;
  md += `   - [ ] \`consent_status\` set in Pre Loader before any tag fires\n`;
  exts.filter(e => e.feedsTag).forEach(e => {
    md += `   - [ ] **${e.feedsTag}** sends on the right events, only when \`${e.tagCategory === 'Marketing' ? 'consent_marketing' : 'consent_analytics'}=1\`\n`;
  });
  policy.protected.protected_variables.filter(v => v !== 'tealium_event').forEach(v => {
    md += `   - [ ] protected var \`${v}\` populated for logged-in users\n`;
  });
  md += `   - [ ] load order matches \`docs/execution-flow.md\`\n\n`;
  md += `> Repo-side validation (\`npm run validate\`) already confirms load order / consent / protected rules **before** deploy. Trace confirms they hold **at runtime** in Tealium.\n`;

  fs.writeFileSync(path.join(ROOT, 'docs/tealium-deployment.md'), md);
  console.log(`✓ Deployment runbook: docs/tealium-deployment.md (${exts.length} extensions, ${Object.keys(profile.tags).length} tags)`);
}

if (require.main === module) run();
module.exports = { run };
