'use strict';
/**
 * Documentation Agent — regenerates human-readable docs from the metadata knowledge
 * base (never from free text). Outputs:
 *   docs/execution-flow.md   — ordered load-order table + mermaid sequence
 *   docs/dependency-map.md   — mermaid graph of extensions -> variables -> tags
 */
const fs = require('fs');
const path = require('path');
const { loadMetadata, ROOT } = require('./lib/load-policy');

function run() {
  const profile = loadMetadata();
  fs.mkdirSync(path.join(ROOT, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'docs/execution-flow.md'), executionFlow(profile));
  fs.writeFileSync(path.join(ROOT, 'docs/dependency-map.md'), dependencyMap(profile));
  console.log('✓ Docs regenerated: docs/execution-flow.md, docs/dependency-map.md');
}

function executionFlow(p) {
  const exts = [...p.extensions].sort((a, b) => a.loadRank - b.loadRank);
  let md = `<!-- GENERATED by scripts/doc-agent.js — do not edit by hand -->\n`;
  md += `# Execution Flow (Load Order)\n\nGenerated ${p.generatedAt} · source: ${p.source}\n\n`;
  md += `Tealium runs extensions by **scope**, then **order** within scope:\n\n`;
  md += `| # | Scope | Order | Extension | Creates | Uses | Risk |\n|---|---|---|---|---|---|---|\n`;
  exts.forEach((e, i) => {
    md += `| ${i + 1} | ${e.scope} | ${e.order} | ${e.name}${e.protected ? ' 🔒' : ''} | ${(e.creates || []).join(', ') || '—'} | ${(e.uses || []).join(', ') || '—'} | ${e.risk} |\n`;
  });
  md += `\n## Sequence\n\n\`\`\`mermaid\nflowchart TD\n`;
  exts.forEach((e, i) => { md += `  E${e.id}["${e.scope}: ${e.name}"]\n`; if (i > 0) md += `  E${exts[i - 1].id} --> E${e.id}\n`; });
  md += `\`\`\`\n`;
  return md;
}

function dependencyMap(p) {
  let md = `<!-- GENERATED by scripts/doc-agent.js — do not edit by hand -->\n`;
  md += `# Dependency Map\n\nGenerated ${p.generatedAt}\n\nExtensions produce variables consumed by other extensions and tags.\n\n`;
  md += `\`\`\`mermaid\ngraph LR\n`;
  p.extensions.forEach(e => {
    (e.creates || []).forEach(v => { md += `  E${e.id}(["${e.name}"]) --> V_${slug(v)}["${v}"]\n`; });
    (e.uses || []).forEach(v => { if (p.variables[v]) md += `  V_${slug(v)} --> E${e.id}\n`; });
    if (e.feedsTag) md += `  E${e.id} --> T_${slug(e.feedsTag)}{{"${e.feedsTag}"}}\n`;
  });
  md += `\`\`\`\n\n## Protected / high-impact variables\n\n`;
  Object.values(p.variables)
    .filter(v => v.usedIn.tags.length)
    .sort((a, b) => b.usedIn.tags.length - a.usedIn.tags.length)
    .forEach(v => { md += `- **${v.name}** → feeds tags: ${v.usedIn.tags.join(', ')} (used by ${v.used_by.length} extension(s))\n`; });
  return md;
}

const slug = s => String(s).replace(/[^a-zA-Z0-9]/g, '_');

if (require.main === module) run();
module.exports = { run };
